# Configuration for local Supabase development
project_id = "tahfizh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/reset-password"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.invite]
subject = "Undangan TAHFIZH"
content_path = "./supabase/templates/invite.html"

[auth.email.template.recovery]
subject = "Reset Password TAHFIZH"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.signup]
subject = "Selamat Datang di TAHFIZH"
content_path = "./supabase/templates/signup.html"
